version: '3'

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8443:8443"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - TZ=Africa/Porto-Novo
      - HTTPS=OFF
      - HTTP_PORT=8000
      - HTTPS_PORT=8443
      - LETSENCRYPT_EMAIL=admin@example.com
      - LETSENCRYPT_HOST=mail.example.com
      - VIRTUAL_HOST=mail.example.com
    volumes:
      - /var/www/mail/data:/data # location ( easy for backup )

